### ISSUE TITLE
[Feature] 有没有考虑出一版纯 UI

### ISSUE THREAD

**Issue by oniLand** [continew-org/continew-admin-ui#18]
### Feature 描述

与后端脱离的纯 showcase，例如 gi-demo 的原始 showcase

### 描述一下您想要的解决方案

就是后端请求使用本地mock数据，和后端脱离，方便前端开发根据业务需求改动。

### 确认

- [X] 阅读[文档](https://continew.top/admin/intro/require.html)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）
- [ ] 您是否愿意为您提出的 Feature 提交 PR？

**Comment by Charles7c** [comment]
你好，由于个人精力有限，所以暂时不考虑。
不过针对此问题，目前提供了一个简单方案：群内有位大佬免费提供了在线 API 服务，可进群联系大佬索要。
![image](https://github.com/Charles7c/continew-admin-ui/assets/25446948/a6cab2b3-5f5f-493f-bcef-0d3837d87142)
