### ISSUE TITLE
[Bug] 代码生成过程前端文件不完整

### ISSUE THREAD

**Issue by mfjiang** [continew-org/continew-admin-ui#22]
### Bug 描述

代码生成过程前端文件不完整，复制生成的前端模块到前端工程，出现类型引用异常

![9c3c5e0f567f113ba742d7cdae0c662](https://github.com/Charles7c/continew-admin-ui/assets/10845183/af255370-ab86-47e7-a1e4-0e0896894dac)

![395d5a734743c7c3b88bf15c753e7db](https://github.com/Charles7c/continew-admin-ui/assets/10845183/d0eae41b-e459-4503-9f16-7d9a048201dd)

### 复现步骤

使用后台代码生成功能

### 预期结果

生成完整的前端模块文件，包括 type.ts,index.ts 等文件

### 环境信息

```markdown
ContiNew Admin version(s):v3.0.1
```

### 确认

- [X] 阅读[文档](https://continew.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by NGbetrue** [comment]
在@apis/index.ts里手动导出一下生成的api文件。如
export * from './system/customer'

**Comment by mfjiang** [comment]
> 在@apis/index.ts里手动引入一下生成的api文件。如 export * from './system/customer'

apis/index.ts 补了 export，但是视图文件仍然有类型问题：
![image](https://github.com/Charles7c/continew-admin-ui/assets/10845183/5f5225fb-5f83-4115-bc08-2d163cbd8f77)

**Comment by Charles7c** [comment]
1、代码生成的代码需要自己手动调整下，不能直接使用，前端 api.ts 生成模板是故意写在一起的，为了方便生成而已，自己参考其他的拆分一下即可。
2、代码生成模板如有需要可自行调整，[模板位置](https://github.com/Charles7c/continew-admin/tree/dev/continew-admin-generator/src/main/resources/templates)
3、使用规范可参考本项目所采用的前端模板：[Gi-Demo](https://gitee.com/lin0716/gi-demo#%E6%8E%A5%E5%8F%A3-api-%E7%9A%84%E5%91%BD%E5%90%8D)
