### ISSUE TITLE
[Bug] 手机端在用户管理页加载不出来数据

### ISSUE THREAD

**Issue by z3597666** [continew-org/continew-admin-ui#24]
### Bug 描述

用官方演示的版本没问题，但是拉官方的代码编译并且上线就有问题
注释掉<UserAddModal ref="UserAddModalRef" @save-success="search" />
    <UserDetailDrawer ref="UserDetailDrawerRef" />
    <UserResetPwdModal ref="UserResetPwdModalRef" />
    问题没了 但是这三功能也没了

### 复现步骤

直接部署 问题就出现  但是在pc的开发者模式调整成手机端就没问题
删除
<UserAddModal ref="UserAddModalRef" @save-success="search" />
    <UserDetailDrawer ref="UserDetailDrawerRef" />
    <UserResetPwdModal ref="UserResetPwdModalRef" />
    也能解决

### 预期结果

不显示数据  我二开的直接跳转黑屏  不显示任何东西 

### 环境信息

```markdown
ContiNew Admin version(s):
```

### 确认

- [X] 阅读[文档](https://continew.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by z3597666** [comment]
补充  安卓没问题   是苹果手机端

**Comment by z3597666** [comment]
补充是browse().isMobile 在苹果浏览器上返回false值

**Comment by z3597666** [comment]
> ### Bug 描述
> 用官方演示的版本没问题，但是拉官方的代码编译并且上线就有问题 注释掉<UserAddModal ref="UserAddModalRef" @save-success="search" /> 问题没了 但是这三功能也没了
> 
> ### 复现步骤
> 直接部署 问题就出现 但是在pc的开发者模式调整成手机端就没问题 删除 <UserAddModal ref="UserAddModalRef" @save-success="search" /> 也能解决
> 
> ### 预期结果
> 不显示数据 我二开的直接跳转黑屏 不显示任何东西
> 
> ### 环境信息
> ```
> ContiNew Admin version(s):
> ```

**Comment by Charles7c** [comment]
没有苹果手机，无法确定相关问题。
