### ISSUE TITLE
[Bug] 前后端无报错，但登陆后页面不存在

### ISSUE THREAD

**Issue by xuzhe521** [continew-org/continew-admin-ui#25]
### Bug 描述

登陆后页面不存在
![image](https://github.com/user-attachments/assets/dabf6ddd-22ab-4655-810c-1f3360b5da07)
![image](https://github.com/user-attachments/assets/4bd6fe13-6628-4ebd-ab23-6dafbe9c5610)
![image](https://github.com/user-attachments/assets/88c333c4-6c6d-493a-b9d2-95dd6e27e867)

### 复现步骤

按文档启动前后端后，登录成功，跳转页面提示找不到

### 预期结果

应能进正确页面

### 环境信息

```markdown
ContiNew Admin version(s):JDK21
node 18.19
浏览器 edge 126.0.2592.113 
```

### 确认

- [X] 阅读[文档](https://continew.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
升级吧，别再用 3.1.0-SNAPSHOT 版本了。
